global:
    config_version: 2
input:
    #type: file
    #path: /root/fio.txt
    #readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
    #fail_on_missing_logfile: true
    type: stdin
grok:
    patterns_dir: ./patterns
    additional_patterns:
    - 'FIO_IOPS [0-9]*[.][0-9]k$|[0-9]*'
metrics:
    - type: gauge
      name: iops_randwrite
      help: FIO IOPS Random Write Gauge Metrics
      match: '  write: IOPS=%{NUMBER:val1}%{GREEDYDATA:thsd}, %{GREEDYDATA}'
      value: '{{if eq .thsd "k"}}{{multiply .val1 1000}}{{else}}{{.val1}}{{end}}'
      labels:
          iops_suffix: '{{.thsd}}'
      cumulative: false
      retention: 1s
    - type: gauge
      name: bandwidth_randwrite
      help: FIO Bandwidth Random Write Gauge Metrics
      match: '  write: IOPS=%{GREEDYDATA}, BW=%{NUMBER:val2}%{GREEDYDATA:kibs} %{GREEDYDATA}'
      value: '{{if eq .kibs "KiB/s"}}{{divide .val2 1024}}{{else}}{{.val2}}{{end}}'
      labels:
          bw_unit: '{{.kibs}}'
      cumulative: false
      retention: 1s
    - type: gauge
      name: avg_latency_randwrite
      help: FIO AVG Latency Random Write Gauge Metrics
      match: '     lat (%{GREEDYDATA:nsec}): min=%{GREEDYDATA}, max=%{GREEDYDATA}, avg=%{NUMBER:val3}, stdev=%{GREEDYDATA}'
      value: '{{if eq .nsec "(nsec)"}}{{divide .val3 1000}}{{else}}{{.val3}}{{end}}'
      labels:
          lat_unit: '{{.nsec}}'
      cumulative: false
      retention: 1s
server:
    host: localhost
    port: 9144
