global:
    config_version: 2
input:
    #type: file
    #path: /root/sumfio.txt
    #readall: true # Read from the beginning of the file? False means we start at the end of the file and read only new lines.
    #fail_on_missing_logfile: true
    #poll_interval_seconds: 1
    type: stdin
grok:
    patterns_dir: ./patterns
    additional_patterns:
    - 'FIO_IOPS [0-9]*[.][0-9]k$|[0-9]*'
metrics:
    - type: gauge
      name: iops_randrw_write
      help: FIO IOPS RandomRW Write Gauge Metrics
      match: '  write: IOPS=%{NUMBER:val1}%{GREEDYDATA:thsd}, %{GREEDYDATA}'
      value: '{{if eq .thsd "k"}}{{multiply .val1 1000}}{{else}}{{.val1}}{{end}}'
      labels:
          parameter: 'IOPS'
      cumulative: false
      retention: 1s
    - type: gauge
      name: bandwidth_randrw_write
      help: FIO Bandwidth RandomRW Write Gauge Metrics
      match: '  write: IOPS=%{GREEDYDATA}, BW=%{NUMBER:val2}%{GREEDYDATA:kibs} %{GREEDYDATA}'
      value: '{{if eq .kibs "KiB/s"}}{{divide .val2 1024}}{{else}}{{.val2}}{{end}}'
      labels:
          bw_unit: 'MiB/s'
      cumulative: false
      retention: 1s
    - type: gauge
      name: avg_latency_randrw_write
      help: FIO AVG Latency RandomRW Write Gauge Metrics
      match: '     lat (%{GREEDYDATA:nsec}): min=%{GREEDYDATA}, max=%{GREEDYDATA}, avg=%{NUMBER:val3}, stdev=%{GREEDYDATA}'
      value: '{{if eq .nsec "(nsec)"}}{{divide .val3 1000}}{{else}}{{.val3}}{{end}}'
      labels:
          lat_unit: 'usec'
      cumulative: false
      retention: 1s
    - type: gauge
      name: iops_randrw_read
      help: FIO IOPS RandomRW Read Gauge Metrics
      match: '  read: IOPS=%{NUMBER:val4}%{GREEDYDATA:thsd}, %{GREEDYDATA}'
      value: '{{if eq .thsd "k"}}{{multiply .val4 1000}}{{else}}{{.val4}}{{end}}'
      labels:
          parameter: 'IOPS'
      cumulative: false
      retention: 1s
    - type: gauge
      name: bandwidth_randrw_read
      help: FIO Bandwidth RandomRW Read Gauge Metrics
      match: '  read: IOPS=%{GREEDYDATA}, BW=%{NUMBER:val5}%{GREEDYDATA:kibs} %{GREEDYDATA}'
      value: '{{if eq .kibs "KiB/s"}}{{divide .val5 1024}}{{else}}{{.val5}}{{end}}'
      labels:
          bw_unit: 'MiB/s'
      cumulative: false
      retention: 1s
server:
    host: localhost
    port: 9144
